server.port=8080
spring.application.name=NSE Stock Fetcher

# Jackson configuration
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.default-property-inclusion=non_null

# Actuator
management.endpoints.web.exposure.include=health,info
